# Generated by Django 4.1.6 on 2023-03-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='material_quantity',
            field=models.ManyToManyField(related_name='material_products', to='inventoryApp.materialquantity'),
        ),
    ]
