# Generated by Django 4.1.6 on 2023-03-22 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='material_stocks',
        ),
        migrations.AlterField(
            model_name='materialquantity',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='inventoryApp.material'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_quantity',
        ),
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='materialstock',
            unique_together={('store', 'material')},
        ),
        migrations.AddField(
            model_name='product',
            name='material_quantity',
            field=models.ManyToManyField(related_name='material_products', to='inventoryApp.materialquantity'),
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='product_stores', to='inventoryApp.product'),
        ),
    ]
