# Generated by Django 4.1.6 on 2023-04-14 02:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SalesHistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.product')),
                ('sales_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.saleshistory')),
            ],
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='products',
            field=models.ManyToManyField(through='inventoryApp.SalesHistoryProduct', to='inventoryApp.product'),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.store'),
        ),
    ]
