# Generated by Django 4.1.6 on 2023-03-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0002_remove_product_material_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material_quantity',
        ),
        migrations.AddField(
            model_name='materialquantity',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity_products', to='inventoryApp.product'),
        ),
    ]
