# Generated by Django 4.1.6 on 2023-03-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0005_alter_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='material_stocks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_stores', to='inventoryApp.materialstock'),
        ),
    ]
