# Generated by Django 4.1.6 on 2023-03-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0006_alter_store_material_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialquantity',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='inventoryApp.material'),
        ),
        migrations.AlterField(
            model_name='store',
            name='material_stocks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_stores', to='inventoryApp.materialstock'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='product_stores', to='inventoryApp.product'),
        ),
    ]
