# Generated by Django 4.1.6 on 2023-03-14 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0008_alter_store_material_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='material_stocks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_stores', to='inventoryApp.materialstock'),
        ),
    ]
