# Generated by Django 4.1.6 on 2023-03-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0009_alter_store_material_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='material_stocks',
        ),
    ]
